##### multifitted ESP field fitting machinery is located here
# TODO: conversation about moving the individual fittin here as well should be had

import numpy as np
from numpy.linalg import lstsq
# https://stackoverflow.com/questions/44508561/algorithm-that-numpy-is-using-for-numpy-linalg-lstsq

from chemistry_data_structure.objects.molecular_entity import Molecule3D


# will probably set the fitter up as an object itself

class MoleculeFieldFitter:
    def __init__(self,
                 molecules: list[Molecule3D]):
        """
        The MoleculeFieldFitter is designed to act as an interactive class for both setting up the system
        and querying the results of the solution
        :param molecules: a list of the chemical data structure molecules
        """
        # maintains a list of the current molecules the system
        self._molecules = molecules
        # statuses
        # unsolved = 0
        # solved = 1
        # error = -1
        self._status = 0
        self._num_constraints = 0
        self._constraint_matrix: np.array = None
        self._coeff_matrix: np.array = None
        self._target_vector: np.array = None
        self._constraint_target: np.array = None
        self._transformed_target: np.array = None
        self._transformed_coeff_matrix: np.array = None
        self._solution: np.array = None
        self._residuals: np.array = None

        self._index_lookup: dict = {}
        self._index_backlookup: dict = {}

    @property
    def status(self):
        return self._status

    @property
    def molecules(self):
        return self._molecules

    @property
    def num_atoms(self):
        return self._coeff_matrix.shape[1]

    def add_molecule(self, molecule: Molecule3D):
        if not isinstance(molecule, Molecule3D):
            raise TypeError('molecule must be of type Molecule3D')
        # TODO: can currently add the same molecule more than once, need to check if this is intended behaviour
        self._molecules.append(molecule)

    def generate_matrices(self):

        # separate out the individual esp and coefficient matrix data
        single_coeffs, single_esps = zip(*[molecule.lsqComponents() for molecule in self._molecules])

        # start generating the system coefficient matrix
        self._coeff_matrix = np.zeros(
            (sum(a.shape[0] for a in single_coeffs), sum(a.shape[1] for a in single_coeffs))
        )
        self._target_vector = np.zeros(
            (sum(a.shape[0] for a in single_coeffs), 1)
        )

        # iteratively populate the diagonals of the coefficient matrix with the individual matrices
        # and iteratively fill the full target esp values, since numpy doesn't natively support ragged shapes
        row_count = 0
        col_count = 0
        for mol_index in range(len(self.molecules)):
            shape = single_coeffs[mol_index].shape

            self._coeff_matrix[row_count:row_count + shape[0],
            col_count:col_count + shape[1]
            ] = single_coeffs[mol_index]
            self._target_vector[row_count:row_count + shape[0]] = single_esps[mol_index]

            # at this generation point also want to generate the index lookup and backlookup dictionaries
            # these will be linked to the internal indexes of the atom orders as they are self consistent

            # iterate over the atom indexes (which are not always super consistent
            # todo: Currently uses the internal indexing (i.e. the index 'id' but the order they appear)
            #  this is at least guaranteed a unique id and it is conistent with the ordering generated by
            #  the esp field and location generation

            # todo need to write a sanity check in the unit tests that confirms this
            for molecule_col_iter in range(self._molecules[mol_index].num_atoms):
                self._index_lookup[
                    self._molecules[mol_index], molecule_col_iter
                ] = col_count + molecule_col_iter

                self._index_backlookup[col_count + molecule_col_iter] = (self._molecules[mol_index], molecule_col_iter)

            row_count += shape[0]
            col_count += shape[1]

    def load_constraints(self,
                         symmetry_constraints: dict,
                         sum_constraints: dict,
                         # index_type: str,
                         ):
        """
        Constraints should be of the form:
        {'group': {molecule_obj}: [internal atom indexes]}
        :param sum_constraints:
        :param symmetry_constraints:
        :return:
        """
        # size of the constraint matrix is given by M+N-G
        # M Molecules (assuming the total charge constraints), N atoms (constrained), G groups

        # https://stackoverflow.com/questions/4391697/find-the-index-of-a-dict-within-a-list-by-matching-the-dicts-value
        # todo Might be lenient with the atom indexing, since the molecules can lookup based on a number of methods
        # todo currently the groups are assumed to be merged, it is known not a trivial thing to implement

        num_constrained_atoms = sum(
            sum(len(atom_list) for atom_list in group_dict.values())
            for group_dict in symmetry_constraints.values()
        )

        self._num_constraints = len(sum_constraints) + num_constrained_atoms - len(symmetry_constraints)

        # need one row for every constraint and one row for every atom
        self._constraint_matrix = np.zeros((self._num_constraints,
                                            self.num_atoms))
        self._constraint_target = np.zeros((self._num_constraints, 1))

        # iterate through the groups, and using the lookup dictionaries to map the molecule atom index
        # to the filters internal matrix columns
        constraint_iter = 0
        for group_name, group_dict in symmetry_constraints.items():
            # flatten out the groups into key,val pair
            flattened_group = [(molecule, atom_index) for molecule, atom_list in group_dict.items()
                               for atom_index in atom_list]

            # iterate through these pairs to utilise the column location lookup
            # assign the appropriate coefficients using the daisy chain approach
            for mol_atom_pair_1, mol_atom_pair_2 in zip(flattened_group[:-1], flattened_group[1:]):
                self._constraint_matrix[constraint_iter,
                                        self._index_lookup[mol_atom_pair_1]] = 1.0
                self._constraint_matrix[constraint_iter,
                                        self._index_lookup[mol_atom_pair_2]] = -1.0

                constraint_iter += 1

        # iterate over the sum constraints, using similar methods for looking up indices
        for sum_dict in sum_constraints:
            flattened_group = [(molecule, atom_index) for molecule, atom_list in sum_dict['atoms'].items()
                               for atom_index in atom_list]
            for mol_atom_pair in flattened_group:
                self._constraint_matrix[constraint_iter, self._index_lookup[mol_atom_pair]] = 1.0
            self._constraint_target[constraint_iter] = sum_dict['value']
            constraint_iter += 1

    def fit(self):
        """
        Function to generate the assigned partial charges
        :return:
        """

        # generate the new matrices used for the fitting procedure (with constraints)

        self._transformed_coeff_matrix = np.zeros(
            (self._num_constraints + self.num_atoms, self._num_constraints + self.num_atoms)
        )

        self._transformed_coeff_matrix[:self.num_atoms, :self.num_atoms] = self._coeff_matrix.T @ self._coeff_matrix
        self._transformed_coeff_matrix[self.num_atoms:, :self.num_atoms] = self._constraint_matrix
        self._transformed_coeff_matrix[:self.num_atoms, self.num_atoms:] = self._constraint_matrix.T

        self._transformed_target = np.zeros((self.num_atoms + self._num_constraints, 1))
        self._transformed_target[:self.num_atoms] = self._coeff_matrix.T @ self._target_vector
        self._transformed_target[self.num_atoms:] = self._constraint_target

        self._solution, self._residuals, rank, singular_values = lstsq(self._transformed_coeff_matrix,
                                                                       self._transformed_target,
                                                                       rcond=None)
        self._status = 1
        return self._solution

    def transfer_partial_charges(self):
        if self._status != 1:
            print('system not yet fitted')
            raise Exception  # todo make a new exception

        for molecule in self.molecules:
            for atom_internal_index in range(molecule.num_atoms):
                molecule.atom_objects[atom_internal_index].partial_charge = \
                    self._solution[self._index_lookup[molecule, atom_internal_index]][0]
